/**
 * Weeklyst — lang.js
 * Alle vertalingen op één plek.
 * Voeg een nieuwe taal toe door een nieuw object toe te voegen.
 * Gebruik in HTML: <span data-i18n="sleutel"></span>
 * Gebruik in JS:   t('sleutel')
 */

const LANG = {

  nl: {
    // ── Algemeen ───────────────────────────────────────────
    back:              '← Terug',
    built_with:        'Gebouwd met',
    version:           'Versie',

    // ── Landing pagina ─────────────────────────────────────
    landing_tagline:   'Slim boodschappen doen met je gezin',
    landing_sub:       'De simpele planner voor maaltijden en boodschappen. Gedeeld met je gezin, altijd up-to-date.',
    landing_f1:        'Gedeelde boodschappenlijst',
    landing_f2:        'Weekmenu plannen',
    landing_f3:        'Ideeën voor avondeten',
    landing_f4:        'Geen reclame, geen tracking',
    landing_register:  'Maak gratis account aan',
    landing_login:     'Inloggen',
    landing_install_hint: 'Hoe zet ik Weeklyst op mijn beginscherm?',
    landing_join:      '🔑 Meedoen met uitnodigingscode',
    landing_donate:    'Vind je Weeklyst handig? Overweeg een donatie',
    join_title:        'Meedoen met een gezin',
    join_sub:          'Vul de gezinscode in die je hebt ontvangen, kies een naam en wachtwoord.',
    nav_about:         'Over',
    nav_privacy:       'Privacy',
    nav_install:       'Installeren',

    // ── Registreren ────────────────────────────────────────
    reg_title:         'Account aanmaken',
    reg_sub:           'Vul je gegevens in om te beginnen.',
    reg_name:          'Naam',
    reg_name_ph:       'Tim',
    reg_email:         'E-mailadres',
    reg_email_ph:      'tim@voorbeeld.nl',
    reg_pass:          'Wachtwoord',
    reg_pass_ph:       'minimaal 8 tekens',
    reg_method:        'Hoe wil je inloggen?',
    reg_method_pw:     'Wachtwoord',
    reg_method_pw_sub: 'Snel inloggen met je wachtwoord',
    reg_method_magic:  'E-mailcode',
    reg_method_magic_sub: 'Elke keer een code per e-mail',
    reg_btn:           'Account aanmaken',
    reg_have_account:  'Al een account?',

    // ── E-mail verificatie ─────────────────────────────────
    verify_title:      'Check je e-mail',
    verify_sub:        'We hebben een 6-cijferige code gestuurd naar',
    verify_label:      'Verificatiecode',
    verify_btn:        'Bevestigen',
    verify_resend:     'Code opnieuw sturen',

    // ── Gezin instellen ────────────────────────────────────
    family_title:      'Je gezin instellen',
    family_sub:        'Maak een nieuw gezin aan of doe mee met een bestaand gezin via een uitnodigingscode.',
    family_name:       'Naam van je gezin',
    family_name_ph:    'Familie De Vries',
    family_create:     'Gezin aanmaken',
    family_or:         'of',
    family_code:       'Uitnodigingscode',
    family_join:       'Meedoen met gezin',

    // ── Uitnodiging ────────────────────────────────────────
    invite_title:      '🎉 Gezin aangemaakt!',
    invite_sub:        'Deel de onderstaande code met je gezinsleden zodat zij kunnen meedoen.',
    invite_code_sub:   'Uitnodigingscode — 6 tekens',
    invite_btn:        'Naar de planner →',
    invite_tip:        'Je kunt de code later ook terugvinden in de instellingen.',

    // ── Inloggen ───────────────────────────────────────────
    login_title:       'Inloggen',
    login_tab_member:      '👨‍👩‍👧 Gezinslid',
    login_tab_hint_member: 'Log in met je gezinscode, naam en wachtwoord.',
    login_tab_hint_owner:  'Log in met je e-mailadres en wachtwoord.',
    login_tab_owner:   '👤 Beheerder',
    forgot_sub_member: 'Vul je naam en gezinscode in. De beheerder ontvangt een resetlink voor jou.',
    forgot_sent_member:'✓ Verzoek verstuurd naar de gezinsbeheerder. Je ontvangt de resetlink via hem/haar.',
    login_sub:         'Welkom terug!',
    login_email:       'E-mailadres',
    login_pass:        'Wachtwoord',
    login_btn:         'Inloggen',
    login_forgot:      'Wachtwoord vergeten?',
    login_no_account:  'Nog geen account?',
    login_signup:      'Aanmelden',

    // ── Magic code ─────────────────────────────────────────
    magic_title:       'Inlogcode',
    magic_sub:         'We hebben een code gestuurd naar',
    magic_label:       'Inlogcode',
    magic_btn:         'Inloggen',
    magic_resend:      'Code opnieuw sturen',

    // ── Wachtwoord vergeten ────────────────────────────────
    forgot_title:      'Wachtwoord vergeten',
    forgot_sub:        'Vul je e-mailadres in en we sturen je een herstelcode.',
    forgot_btn:        'Code sturen',
    forgot_back:       '← Terug naar inloggen',

    // ── Wachtwoord resetten ────────────────────────────────
    reset_title:       'Nieuw wachtwoord',
    reset_sub:         'Voer de code in uit je e-mail en kies een nieuw wachtwoord.',
    reset_code:        'Herstelcode',
    reset_pass:        'Nieuw wachtwoord',
    reset_btn:         'Wachtwoord instellen',

    // ── App: secties ───────────────────────────────────────
    app_meals:         'Wat gaan we eten?',
    app_shops:         'Boodschappen',
    app_ideas:         'Ideeën voor avondeten',
    app_add_shop:      '＋ artikel toevoegen',
    app_add_idea:      '＋ idee toevoegen',
    app_meal_ph:       'wat eten we?',
    app_shop_ph:       'artikel…',
    app_store_ph:      'winkel',
    app_idea_ph:       'idee voor avondeten…',
    app_title_ph:      'Lijsttitel…',
    app_who_ph:        'Wie doet de boodschappen?',
    app_offline:       '⚠ Geen internetverbinding — wijzigingen worden opgeslagen zodra je weer online bent',

    // ── App: status ────────────────────────────────────────
    status_loading:    'Laden…',
    status_synced:     'Gesynchroniseerd',
    status_saved:      'Opgeslagen',
    status_updated:    'Bijgewerkt',
    status_saving:     'Opslaan…',
    status_save_error: 'Opslaan mislukt',
    status_updated_by: 'Bijgewerkt door',
    btn_saved:         '✓ Opgeslagen',
    btn_save_error:    '✗',

    // ── Instellingen ───────────────────────────────────────
    settings_title:    'Instellingen',
    settings_family:   'Gezin',
    settings_save_name:'Naam opslaan',
    settings_invite:     'Gezinscode',
    settings_invite_btn: 'Uitnodigen',
    invite_link_copied:  '✓ Uitnodigingslink gekopieerd! Plak hem in WhatsApp of een berichtje.',
    settings_members:  'Gezinsleden',
    settings_push:       'Meldingen',
    settings_push_sub:   'Ontvang een melding wanneer een gezinslid de lijst heeft bijgewerkt.',
    push_enable:         'Meldingen inschakelen',
    push_disable:        'Meldingen uitschakelen',
    push_enabled:        '✓ Meldingen ingeschakeld! Je ontvangt voortaan een seintje na een update.',
    push_disabled:       '✓ Meldingen uitgeschakeld.',
    push_denied:         'Je hebt meldingen geblokkeerd. Pas dit aan in je browserinstellingen.',
    push_not_supported:  'Push notificaties worden niet ondersteund op dit apparaat.',
    push_error:          'Inschakelen mislukt. Probeer opnieuw.',
    settings_cards:      'Klantenkaarten',
    settings_add_card: '＋ Kaart toevoegen',
    card_add_title:    'Kaart toevoegen',
    card_shop_name:    'Winkelnaam',
    card_code:         'Kaartnummer / code',
    card_type:         'Type',
    card_type_hint_ean:'EAN-13: 13 cijfers, bijv. AH bonuskaart',
    card_type_hint_128:'Code 128: letters en cijfers, bijv. ANWB',
    card_type_hint_qr: 'QR-code: bijv. Praxis voordeelkaart',
    card_color:        'Kleur',
    card_save:         'Kaart opslaan',
    card_scan:         '📷 Scan via camera',
    card_empty:        'Nog geen kaarten toegevoegd.',
    card_err_code:     'Vul een kaartnummer in.',
    close:             'Sluiten',
    member_owner:      'beheerder',
    member_make_owner:   'Maak beheerder',
    member_remove_owner: 'Beheerdersrechten intrekken',
    member_remove:     'Verwijder uit gezin',
    settings_invite_sub:'Deel deze code met gezinsleden om mee te doen.',
    settings_copy:     'Kopieer',
    settings_copied:   'Code gekopieerd!',
    settings_week_label:  'Week',
    settings_week_start:  'Week begint op',
    day_monday:    'Maandag',
    day_tuesday:   'Dinsdag',
    day_wednesday: 'Woensdag',
    day_thursday:  'Donderdag',
    day_friday:    'Vrijdag',
    day_saturday:  'Zaterdag',
    day_sunday:    'Zondag',
    settings_new_week: 'Nieuwe week',
    settings_week_info:'Wist de boodschappenlijst voor een nieuwe week. De maaltijden en ideeën blijven bewaard.',
    settings_week_btn: '📅 Nieuwe week starten',
    settings_week_confirm: 'Boodschappenlijst leegmaken voor een nieuwe week?\n\nDe maaltijden en ideeën blijven bewaard.',
    settings_week_done:'Nieuwe week gestart!',
    settings_pw:       'Wachtwoord wijzigen',
    settings_pw_old:   'Huidig wachtwoord',
    settings_pw_new:   'Nieuw wachtwoord (min. 8 tekens)',
    settings_pw_btn:   'Wachtwoord wijzigen',
    settings_pw_done:  'Wachtwoord gewijzigd!',
    settings_display:  'Weergave',
    settings_light:    '☀️ Licht',
    settings_dark:     '🌙 Donker',
    settings_auto:     '🌓 Auto',
    settings_lang:     'Taal',
    settings_logout:   'Uitloggen',
    settings_about:    'Over Weeklyst',
    settings_privacy:  'Privacy',
    settings_install:  '❓ Installeren',
    settings_update:       'Update',
    settings_version:      'Versie',
    settings_check_update: '🔄 Controleer op update',
    settings_delete_label: 'Account opzeggen',
    settings_leave_label:  'Gezin verlaten',
    settings_leave_info:   'Verwijder jezelf uit het gezin. Je account wordt permanent verwijderd.',
    settings_leave_btn:    'Gezin verlaten',
    leave_confirm:         'Weet je zeker dat je het gezin wilt verlaten? Je account wordt permanent verwijderd.',
    settings_delete_info:  'Stuur een verzoek om je gezin en alle accounts te verwijderen. Je ontvangt een bevestiging per e-mail.',
    settings_delete_btn:   '🗑️ Account opzeggen',
    delete_popup_title:    'Account opzeggen',
    delete_popup_text:     'Dit stuurt een verwijderverzoek naar de beheerder. Alle gezinsleden en data worden daarna verwijderd. Dit kan niet ongedaan worden gemaakt.',
    delete_popup_confirm:  'Ja, ik wil het account en alle gezinsdata permanent laten verwijderen.',
    delete_popup_cancel:   'Annuleren',
    delete_popup_send:     'Verzoek sturen',
    delete_sent:           'Verzoek verstuurd. Je ontvangt een bevestiging per e-mail zodra het account is verwijderd.',

    // ── Foutmeldingen ──────────────────────────────────────
    err_name:          'Vul je naam in.',
    err_email:         'Vul je e-mailadres in.',
    err_email_invalid: 'Ongeldig e-mailadres.',
    err_pass_short:    'Wachtwoord moet minimaal 6 tekens zijn.',
    err_code:          'Voer de 6-cijferige code in.',
    err_family_name:   'Vul een naam in voor je gezin.',
    err_invite_code:   'Voer een geldige uitnodigingscode in (6 tekens).',
    err_connection:    'Verbindingsfout, probeer opnieuw.',
    err_login:         'Inloggen mislukt.',
    err_wrong_pw:      'Huidig wachtwoord onjuist.',
    err_new_pw_short:  'Nieuw wachtwoord minimaal 8 tekens.',
    err_fill_pw:       'Vul je huidige wachtwoord in.',
    err_fill_pw_login: 'Vul je wachtwoord in.',
    err_family_short:  'Naam te kort.',
    msg_resend_ok:     'Nieuwe code verstuurd!',
    msg_forgot_sent:   'Als dit e-mailadres bekend is, ontvang je een code. Controleer ook je spammap.',
    msg_pw_reset_ok:   'Wachtwoord gewijzigd! Je kunt nu inloggen.',
    msg_updated_by:    '✓ Bijgewerkt door',

    // ── Over pagina ────────────────────────────────────────
    about_title:       'Over Weeklyst',
    about_s1_title:    'Over Weeklyst',
    about_s1_text:     'Weeklyst is ontstaan uit een simpele behoefte: een gedeelde boodschappenlijst voor het gezin, zonder gedoe. Geen reclame, geen tracking, geen overbodige functies — gewoon een overzichtelijke planner voor maaltijden en boodschappen die iedereen in het gezin kan bijhouden.',
    about_s2_title:    '💡 Het idee',
    about_s2_text:     'Veel gezinnen plannen hun boodschappen nog via een gedeelde notitie op de telefoon. Dat werkt, maar het kan slimmer. Weeklyst biedt precies dat — niet meer, niet minder.',
    about_s3_title:    '🤖 Gebouwd samen met Claude.ai',
    about_s3_text:     'Weeklyst is ontwikkeld in samenwerking met Claude.ai, de AI-assistent van Anthropic. Het idee, de vormgeving en de functionaliteit zijn bedacht door een mens — Claude heeft geholpen om dat idee snel en vakkundig in code om te zetten. Een mooie samenwerking tussen menselijke creativiteit en AI.',
    about_s4_title:    '🔓 Privacy eerst',
    about_s4_text:     'Jouw data blijft van jou. Geen advertenties, geen verkoop van gegevens, geen tracking. Weeklyst slaat alleen op wat nodig is om de app te laten werken. Alles staat op een Nederlandse server.',
    about_s4_link:     'Lees de volledige privacy policy →',
    about_donate_title:'☕ Donatie',
    about_donate_text: 'Weeklyst is gratis te gebruiken. Vind je het handig? Een kleine donatie helpt om de app draaiende te houden en verder te ontwikkelen.',
    about_donate_btn:  '☕ Doneer via Ko-fi',
    about_version:     'Versie',
    about_new_title:   '🆕 Wat is er nieuw?',
    about_new_check_title: '✓ Boodschappen afvinken',
    about_new_check_text:  'Tijdens het boodschappen doen kun je artikelen afvinken zonder ze te verwijderen. Tik op het rondje voor een artikel om het te markeren als "in het karretje". Het item blijft zichtbaar maar wordt doorgestreept — zo zie jij én je gezinsleden precies wat er al is gepakt. Tik nogmaals om het vinkje te verwijderen.',
    about_new_version_title: '🔄 Automatische updates',
    about_new_version_text:  'Weeklyst krijgt regelmatig kleine verbeteringen. Wanneer er een update beschikbaar is zie je rechtsonder in de app een melding. Tik daarop om de app te vernieuwen — je hoeft de app niet te verwijderen en opnieuw toe te voegen aan je beginscherm.',
    about_new_login_title:   '👨‍👩‍👧 Vereenvoudigd meedoen',
    about_new_login_text:    'Gezinsleden hebben geen eigen e-mailadres meer nodig om deel te nemen. Meedoen gaat nu met alleen een gezinscode, een naam en een wachtwoord. Inloggen werkt daarna op dezelfde manier. De gezinsbeheerder blijft aanmelden met e-mailadres en wachtwoord. Bij een vergeten wachtwoord stuurt het systeem een resetlink naar de beheerder, die deze kan doorsturen naar het gezinslid.',
    about_new_cards_title:   '🏪 Klantenkaarten',
    about_new_cards_text:    'Sla je bonus- en voordeelkaarten op in de app. Scan de barcode of QR-code via de camera van je telefoon, of voer het nummer handmatig in. Tik op een kaart om hem groot op het scherm te tonen bij de kassa. Ondersteunt streepjescodes (EAN-13, Code 128) en QR-codes, zoals die van de AH, ANWB, Gamma, Karwei en Praxis. De kaarten zijn zichtbaar voor het hele gezin.',
    about_new_security_title: '🔒 Extra beveiliging op formulieren',
    about_new_security_text:  'Alle formulieren in de app zijn voorzien van extra beveiligingslagen die geautomatiseerde aanvallen detecteren en blokkeren. Dit werkt volledig op de achtergrond en is niet merkbaar voor gewone gebruikers.',
    about_new_push_title:     '🔔 Push notificaties',
    about_new_push_text:      'Ontvang een melding op je telefoon wanneer een gezinslid de lijst heeft bijgewerkt. De app wacht 2 minuten na de laatste wijziging voor de melding verstuurd wordt — zo krijg je één melding per bewerkingssessie in plaats van bij iedere kleine aanpassing. Op het app-icoon verschijnt ook een rood bolletje. Meldingen zijn opt-in: je kunt ze inschakelen via Instellingen.',
    about_new_invite_title:   '🔗 Uitnodigen via link',
    about_new_invite_text:    'Gezinsleden uitnodigen gaat nu nog eenvoudiger. Tik op de knop "Uitnodigen" in Instellingen en deel de link via WhatsApp, iMessage of e-mail. De ontvanger hoeft alleen nog een naam en wachtwoord in te vullen — de gezinscode zit al verwerkt in de link.',
    about_new_owners_title:   '👑 Meerdere beheerders',
    about_new_owners_text:    'Je kunt meerdere gezinsleden beheerder maken, net zoals je bij WhatsApp meerdere groepseigenaren kunt hebben. Beheerders kunnen leden toevoegen, verwijderen en de beheerdersrol toekennen of intrekken. Gewone leden kunnen het gezin verlaten via Instellingen.',
    about_new_days_title:     '📅 Vaste weekdagen en begindag instellen',
    about_new_days_text:      'De dagen in de weekplanner zijn nu vaste namen (Ma, Di, Wo...) in plaats van vrij tekstveld. In de instellingen kun je kiezen op welke dag jouw week begint — de overige dagen worden automatisch in de juiste volgorde ingevuld. De huidige dag wordt vetgedrukt weergegeven zodat je hem direct herkent.',
    about_new_week_reset_title: '🛒 Nieuwe week wist alleen boodschappen',
    about_new_week_reset_text:  'Wanneer je een nieuwe week start worden alleen de boodschappen gewist. De weekplanner met maaltijden en de ideeënlijst blijven volledig bewaard — handig om terug te kijken wat je de week ervoor hebt gegeten.',
    about_new_scroll_title:   '🔴 Klik op versienummer om update te starten',
    about_new_scroll_text:    'Wanneer er een update beschikbaar is verschijnt er een rood bolletje bij het versienummer onderaan de app. Tik daarop en de instellingen openen zich automatisch met de update-knop in beeld — je hoeft zelf niet meer te scrollen.',

    // ── Installatie pagina ─────────────────────────────────
    install_title:     '📱 Weeklyst installeren',
    install_sub:       'Voeg Weeklyst toe aan je beginscherm voor de beste ervaring — werkt als een echte app, zonder de App Store.',
    install_tab_ios:   '🍎 iPhone / iPad',
    install_tab_android: '🤖 Android',
    install_ios_1_title: 'Open Safari',
    install_ios_1_text:  'Ga naar <strong>weeklyst.nl</strong> in Safari op je iPhone of iPad.<br><em>Let op: gebruik Safari, niet Chrome of een andere browser.</em>',
    install_ios_2_title: 'Tik op het Delen icoon',
    install_ios_2_text:  'Tik onderaan je scherm op het <span class="step-icon">&#11014;</span> icoon (vierkantje met pijltje omhoog).',
    install_ios_3_title: 'Kies "Zet op beginscherm"',
    install_ios_3_text:  'Scroll in het menu omlaag en tik op <strong>"Zet op beginscherm"</strong> (met een &#10133; icoon).',
    install_ios_4_title: 'Tik op "Voeg toe"',
    install_ios_4_text:  'De naam staat al op "Weeklyst". Tik rechtsboven op <strong>"Voeg toe"</strong>.',
    install_ios_5_title: 'Klaar! 🎉',
    install_ios_5_text:  'Weeklyst staat nu op je beginscherm als een echte app met het blauwe mandje-icoon.',
    install_ios_tip:     '<strong>Tip:</strong> Open de app altijd via het beginscherm-icoon voor de beste ervaring. Push-notificaties werken ook alleen als je de app zo opent.',
    install_and_1_title: 'Open Chrome',
    install_and_1_text:  'Ga naar <strong>weeklyst.nl</strong> in Google Chrome op je Android telefoon of tablet.',
    install_and_2_title: 'Tik op het menu',
    install_and_2_text:  'Tik op de drie puntjes <span class="step-icon">&#8942;</span> rechtsboven in Chrome.',
    install_and_3_title: 'Kies "Toevoegen aan startscherm"',
    install_and_3_text:  'Tik op <strong>"Toevoegen aan startscherm"</strong> of <strong>"App installeren"</strong> in het menu.',
    install_and_4_title: 'Bevestig',
    install_and_4_text:  'Tik op <strong>"Toevoegen"</strong> in het popup venster.',
    install_and_5_title: 'Klaar! 🎉',
    install_and_5_text:  'Weeklyst staat nu op je startscherm. Je vindt het icoon tussen je andere apps.',
    install_and_tip:     '<strong>Samsung browser?</strong> Tik op de drie streepjes onderaan → "Pagina toevoegen aan" → "Startscherm".',
    install_benefits_title: 'Waarom toevoegen aan je beginscherm?',
    install_b1:          'Sneller opstarten — direct naar de app',
    install_b2:          'Voelt als een echte app — zonder adresbalk',
    install_b3:          'Altijd bij de hand voor je gezin',
    install_b4:          'Geen App Store nodig — gratis en altijd up-to-date',

    // ── Privacy pagina ─────────────────────────────────────
    privacy_title:      'Privacy Policy',
    privacy_date:       'Versie 1.0 — Juni 2025',
    privacy_summary_label: 'Kort samengevat:',
    privacy_summary_text: 'Weeklyst slaat alleen op wat nodig is om de app te laten werken. Geen reclame, geen tracking, geen verkoop van jouw gegevens. Jouw data blijft in Nederland.',
    privacy_summary:    'Kort samengevat: Weeklyst slaat alleen op wat nodig is om de app te laten werken. Geen reclame, geen tracking, geen verkoop van jouw gegevens. Jouw data blijft in Nederland.',
    privacy_s1_title:   '1. Wie zijn wij?',
    privacy_s1_text:    'Weeklyst is een persoonlijk project — een simpele gezinsplanner voor maaltijden en boodschappen. De app is ontwikkeld door een particulier en wordt gehost op Nederlandse servers.',
    privacy_s1_text:    'Weeklyst is een persoonlijk project — een simpele gezinsplanner voor maaltijden en boodschappen, gehost op Nederlandse servers.',
    privacy_contact:    'Contact:',
    privacy_s2_title:   '2. Welke gegevens slaan we op?',
    privacy_s2_intro:   'We slaan alleen de gegevens op die nodig zijn om de app te laten werken:',
    privacy_s2_1:       'Je e-mailadres (voor inloggen en verificatie)',
    privacy_s2_2:       'Je naam (wordt getoond in de app bij wijzigingen)',
    privacy_s2_3:       'De naam van je gezin',
    privacy_s2_4:       'De inhoud van je weekplanner (maaltijden, boodschappen, ideeën)',
    privacy_s2_5:       'Een versleuteld wachtwoord (alleen bij wachtwoord-login)',
    privacy_s3_title:   '3. Wat doen we NIET?',
    privacy_s3_1:       'We verkopen jouw gegevens niet aan derden',
    privacy_s3_2:       'We gebruiken geen advertenties of advertentienetwerken',
    privacy_s3_3:       'We tracken jouw gedrag niet (geen Google Analytics, geen pixels)',
    privacy_s3_4:       'We delen jouw gegevens niet met andere bedrijven',
    privacy_s3_5:       'We sturen geen marketing e-mails',
    privacy_s4_title:   '4. Waar staat jouw data?',
    privacy_s4_text:    'Alle gegevens worden opgeslagen op een server in Nederland bij Antagonist, een Nederlandse hostingprovider. De data verlaat Nederland niet.',
    privacy_s4_text:    'Alle gegevens worden opgeslagen op een server in Nederland bij Antagonist, een Nederlandse hostingprovider. De data verlaat Nederland niet.',
    privacy_s5_title:   '5. Hoe lang bewaren we jouw gegevens?',
    privacy_s5_text:    'Jouw gegevens worden bewaard zolang je account actief is. Wanneer je je account verwijdert, worden alle bijbehorende gegevens permanent gewist binnen 30 dagen.',
    privacy_s5_text:    'Jouw gegevens worden bewaard zolang je account actief is. Wanneer je je account verwijdert, worden alle bijbehorende gegevens permanent gewist binnen 30 dagen.',
    privacy_s6_title:   '6. Cookies',
    privacy_s6_text:    'Weeklyst uses one functional cookie to keep you logged in. This cookie contains no personal information and is not used for tracking or advertising. The cookie automatically expires after 30 days or when you log out.',
    privacy_s6_text:    'Weeklyst gebruikt één functioneel cookie om je ingelogd te houden. Dit cookie bevat geen persoonlijke informatie en wordt niet gebruikt voor tracking of advertenties. Het cookie verdwijnt automatisch na 30 dagen of wanneer je uitlogt.',
    privacy_s6_text:    'Weeklyst gebruikt één functioneel cookie om je ingelogd te houden. Dit cookie bevat geen persoonlijke informatie en wordt niet gebruikt voor tracking of advertenties. Het cookie verdwijnt automatisch na 30 dagen of wanneer je uitlogt.',
    privacy_s7_title:   '7. Beveiliging',
    privacy_s7_text:    'Alle verbindingen met Weeklyst verlopen via HTTPS. Wachtwoorden worden versleuteld opgeslagen met een sterk algoritme (bcrypt). Sessies worden beveiligd met een gesigneerd cookie.',
    privacy_s7_text:    'Alle verbindingen met Weeklyst verlopen via HTTPS. Wachtwoorden worden versleuteld opgeslagen met een sterk algoritme (bcrypt). Sessies worden beveiligd met een gesigneerd cookie.',
    privacy_s8_title:   '8. Jouw rechten (AVG/GDPR)',
    privacy_s8_intro:   'Op grond van de AVG heb je de volgende rechten:',
    privacy_s8_1:       'Recht op inzage van jouw gegevens',
    privacy_s8_2:       'Recht op correctie van onjuiste gegevens',
    privacy_s8_3:       'Recht op verwijdering van jouw gegevens',
    privacy_s8_4:       'Recht op dataportabiliteit',
    privacy_s8_5:       'Recht om bezwaar te maken',
    privacy_s8_outro:   'Neem contact op via info@weeklyst.nl om een verzoek in te dienen. We reageren binnen 30 dagen.',
    privacy_s9_title:   '9. Wijzigingen',
    privacy_s9_text:    'We kunnen deze privacy policy aanpassen. Bij belangrijke wijzigingen word je via e-mail op de hoogte gesteld. De datum bovenaan de pagina geeft aan wanneer de policy voor het laatst is bijgewerkt.',
    privacy_s9_text:    'We kunnen deze privacy policy aanpassen. Bij belangrijke wijzigingen word je via e-mail op de hoogte gesteld.',
    privacy_s10_title:  '10. Contact',
    privacy_s10_text:   'Do you have questions about your privacy or want to submit a request?',
    privacy_s10_text:   'Heb je vragen over jouw privacy of wil je een verzoek indienen?',
    privacy_s10_text:   'Heb je vragen over jouw privacy of wil je een verzoek indienen?',
    privacy_s10_email:  'E-mail:',
  },

  en: {
    // ── Algemeen ───────────────────────────────────────────
    back:              '← Back',
    built_with:        'Built with',
    version:           'Version',

    // ── Landing pagina ─────────────────────────────────────
    landing_tagline:   'Smart grocery shopping with your family',
    landing_sub:       'The simple planner for meals and groceries. Shared with your family, always up-to-date.',
    landing_f1:        'Shared grocery list',
    landing_f2:        'Plan your weekly menu',
    landing_f3:        'Dinner ideas',
    landing_f4:        'No ads, no tracking',
    landing_register:  'Create free account',
    landing_login:     'Log in',
    landing_install_hint: 'How do I add Weeklyst to my home screen?',
    landing_join:      '🔑 Join with invite code',
    landing_donate:    'Find Weeklyst useful? Consider a donation',
    join_title:        'Join a family',
    join_sub:          'Enter the family code you received, choose a name and password.',
    nav_about:         'About',
    nav_privacy:       'Privacy',
    nav_install:       'Install',

    // ── Registreren ────────────────────────────────────────
    reg_title:         'Create account',
    reg_sub:           'Fill in your details to get started.',
    reg_name:          'Name',
    reg_name_ph:       'Tim',
    reg_email:         'Email address',
    reg_email_ph:      'tim@example.com',
    reg_pass:          'Password',
    reg_pass_ph:       'at least 8 characters',
    reg_method:        'How would you like to log in?',
    reg_method_pw:     'Password',
    reg_method_pw_sub: 'Quick login with your password',
    reg_method_magic:  'Email code',
    reg_method_magic_sub: 'Receive a code by email each time',
    reg_btn:           'Create account',
    reg_have_account:  'Already have an account?',

    // ── E-mail verificatie ─────────────────────────────────
    verify_title:      'Check your email',
    verify_sub:        'We sent a 6-digit code to',
    verify_label:      'Verification code',
    verify_btn:        'Confirm',
    verify_resend:     'Resend code',

    // ── Gezin instellen ────────────────────────────────────
    family_title:      'Set up your family',
    family_sub:        'Create a new family or join an existing one with an invite code.',
    family_name:       'Family name',
    family_name_ph:    'The Smith Family',
    family_create:     'Create family',
    family_or:         'or',
    family_code:       'Invite code',
    family_join:       'Join family',

    // ── Uitnodiging ────────────────────────────────────────
    invite_title:      '🎉 Family created!',
    invite_sub:        'Share the code below with your family members so they can join.',
    invite_code_sub:   'Invite code — 6 characters',
    invite_btn:        'Go to planner →',
    invite_tip:        'You can find this code later in settings.',

    // ── Inloggen ───────────────────────────────────────────
    login_title:       'Log in',
    login_tab_member:      '👨‍👩‍👧 Family member',
    login_tab_hint_member: 'Log in with your family code, name and password.',
    login_tab_hint_owner:  'Log in with your email address and password.',
    login_tab_owner:   '👤 Admin',
    forgot_sub_member: 'Enter your name and family code. The admin will receive a reset link for you.',
    forgot_sent_member:'✓ Request sent to the family admin. You will receive the reset link from them.',
    login_sub:         'Welcome back!',
    login_email:       'Email address',
    login_pass:        'Password',
    login_btn:         'Log in',
    login_forgot:      'Forgot password?',
    login_no_account:  'No account yet?',
    login_signup:      'Sign up',

    // ── Magic code ─────────────────────────────────────────
    magic_title:       'Login code',
    magic_sub:         'We sent a code to',
    magic_label:       'Login code',
    magic_btn:         'Log in',
    magic_resend:      'Resend code',

    // ── Wachtwoord vergeten ────────────────────────────────
    forgot_title:      'Forgot password',
    forgot_sub:        'Enter your email and we will send you a recovery code.',
    forgot_btn:        'Send code',
    forgot_back:       '← Back to login',

    // ── Wachtwoord resetten ────────────────────────────────
    reset_title:       'New password',
    reset_sub:         'Enter the code from your email and choose a new password.',
    reset_code:        'Recovery code',
    reset_pass:        'New password',
    reset_btn:         'Set password',

    // ── App: secties ───────────────────────────────────────
    app_meals:         'What are we eating?',
    app_shops:         'Groceries',
    app_ideas:         'Dinner ideas',
    app_add_shop:      '＋ add item',
    app_add_idea:      '＋ add idea',
    app_meal_ph:       'what are we eating?',
    app_shop_ph:       'item…',
    app_store_ph:      'store',
    app_idea_ph:       'dinner idea…',
    app_title_ph:      'List title…',
    app_who_ph:        'Who does the shopping?',
    app_offline:       '⚠ No internet connection — changes will be saved when you are back online',

    // ── App: status ────────────────────────────────────────
    status_loading:    'Loading…',
    status_synced:     'Synchronized',
    status_saved:      'Saved',
    status_updated:    'Updated',
    status_saving:     'Saving…',
    status_save_error: 'Save failed',
    status_updated_by: 'Updated by',
    btn_saved:         '✓ Saved',
    btn_save_error:    '✗',

    // ── Instellingen ───────────────────────────────────────
    settings_title:    'Settings',
    settings_family:   'Family',
    settings_save_name:'Save name',
    settings_invite:     'Family code',
    settings_invite_btn: 'Invite',
    invite_link_copied:  '✓ Invite link copied! Paste it in WhatsApp or a message.',
    settings_members:  'Family members',
    settings_push:       'Notifications',
    settings_push_sub:   'Receive a notification when a family member has updated the list.',
    push_enable:         'Enable notifications',
    push_disable:        'Disable notifications',
    push_enabled:        '✓ Notifications enabled! You will receive a nudge after an update.',
    push_disabled:       '✓ Notifications disabled.',
    push_denied:         'You have blocked notifications. Change this in your browser settings.',
    push_not_supported:  'Push notifications are not supported on this device.',
    push_error:          'Failed to enable. Please try again.',
    settings_cards:      'Loyalty cards',
    settings_add_card: '＋ Add card',
    card_add_title:    'Add card',
    card_shop_name:    'Store name',
    card_code:         'Card number / code',
    card_type:         'Type',
    card_type_hint_ean:'EAN-13: 13 digits, e.g. AH bonus card',
    card_type_hint_128:'Code 128: letters and digits, e.g. ANWB',
    card_type_hint_qr: 'QR code: e.g. Praxis loyalty card',
    card_color:        'Color',
    card_save:         'Save card',
    card_scan:         '📷 Scan via camera',
    card_empty:        'No cards added yet.',
    card_err_code:     'Please enter a card number.',
    close:             'Close',
    member_owner:      'admin',
    member_make_owner:   'Make admin',
    member_remove_owner: 'Remove admin rights',
    member_remove:     'Remove from family',
    settings_invite_sub:'Share this code with family members to join.',
    settings_copy:     'Copy',
    settings_copied:   'Code copied!',
    settings_week_label:  'Week',
    settings_week_start:  'Week starts on',
    day_monday:    'Monday',
    day_tuesday:   'Tuesday',
    day_wednesday: 'Wednesday',
    day_thursday:  'Thursday',
    day_friday:    'Friday',
    day_saturday:  'Saturday',
    day_sunday:    'Sunday',
    settings_new_week: 'New week',
    settings_week_info:'Clears the shopping list for a new week. Meals and ideas are kept.',
    settings_week_btn: '📅 Start new week',
    settings_week_confirm: 'Clear the shopping list for a new week?\n\nMeals and ideas will be kept.',
    settings_week_done:'New week started!',
    settings_pw:       'Change password',
    settings_pw_old:   'Current password',
    settings_pw_new:   'New password (min. 8 characters)',
    settings_pw_btn:   'Change password',
    settings_pw_done:  'Password changed!',
    settings_display:  'Display',
    settings_light:    '☀️ Light',
    settings_dark:     '🌙 Dark',
    settings_auto:     '🌓 Auto',
    settings_lang:     'Language',
    settings_logout:   'Log out',
    settings_about:    'About Weeklyst',
    settings_privacy:  'Privacy',
    settings_install:  '❓ Install',
    settings_update:       'Update',
    settings_version:      'Version',
    settings_check_update: '🔄 Check for update',
    settings_delete_label: 'Delete account',
    settings_leave_label:  'Leave family',
    settings_leave_info:   'Remove yourself from the family. Your account will be permanently deleted.',
    settings_leave_btn:    'Leave family',
    leave_confirm:         'Are you sure you want to leave the family? Your account will be permanently deleted.',
    settings_delete_info:  'Send a request to delete your family and all accounts. You will receive a confirmation by email.',
    settings_delete_btn:   '🗑️ Delete account',
    delete_popup_title:    'Delete account',
    delete_popup_text:     'This sends a deletion request to the administrator. All family members and data will then be deleted. This cannot be undone.',
    delete_popup_confirm:  'Yes, I want to permanently delete the account and all family data.',
    delete_popup_cancel:   'Cancel',
    delete_popup_send:     'Send request',
    delete_sent:           'Request sent. You will receive a confirmation by email once the account has been deleted.',

    // ── Foutmeldingen ──────────────────────────────────────
    err_name:          'Please enter your name.',
    err_email:         'Please enter your email address.',
    err_email_invalid: 'Invalid email address.',
    err_pass_short:    'Password must be at least 6 characters.',
    err_code:          'Please enter the 6-digit code.',
    err_family_name:   'Please enter a name for your family.',
    err_invite_code:   'Please enter a valid invite code (6 characters).',
    err_connection:    'Connection error, please try again.',
    err_login:         'Login failed.',
    err_wrong_pw:      'Current password is incorrect.',
    err_new_pw_short:  'New password must be at least 8 characters.',
    err_fill_pw:       'Please enter your current password.',
    err_fill_pw_login: 'Please enter your password.',
    err_family_short:  'Name is too short.',
    msg_resend_ok:     'New code sent!',
    msg_forgot_sent:   'If this email address is known, you will receive a code. Check your spam folder too.',
    msg_pw_reset_ok:   'Password changed! You can now log in.',
    msg_updated_by:    '✓ Updated by',

    // ── Over pagina ────────────────────────────────────────
    about_title:       'About Weeklyst',
    about_s1_title:    'About Weeklyst',
    about_s1_text:     'Weeklyst was born from a simple need: a shared grocery list for the family, without hassle. No ads, no tracking, no unnecessary features — just a clear planner for meals and groceries that everyone in the family can use.',
    about_s2_title:    '💡 The idea',
    about_s2_text:     'Many families still plan their groceries through a shared note on their phone. That works, but it can be smarter. Weeklyst offers exactly that — nothing more, nothing less.',
    about_s3_title:    '🤖 Built together with Claude.ai',
    about_s3_text:     'Weeklyst was developed in collaboration with Claude.ai, the AI assistant from Anthropic. The idea, the design and the functionality were conceived by a human — Claude helped to quickly and professionally translate that idea into code. A great collaboration between human creativity and AI.',
    about_s4_title:    '🔓 Privacy first',
    about_s4_text:     'Your data is yours. No ads, no selling of data, no tracking. Weeklyst only stores what is needed to make the app work. Everything is stored on a Dutch server.',
    about_s4_link:     'Read the full privacy policy →',
    about_donate_title:'☕ Donation',
    about_donate_text: 'Weeklyst is free to use. Find it useful? A small donation helps keep the app running and developing further.',
    about_donate_btn:  '☕ Donate via Ko-fi',
    about_version:     'Version',
    about_new_title:   '🆕 What\'s new?',
    about_new_check_title: '✓ Check off groceries',
    about_new_check_text:  'While shopping you can check off items without deleting them. Tap the circle next to an item to mark it as "in the cart". The item stays visible but gets crossed out — so you and your family can see exactly what has already been picked up. Tap again to uncheck.',
    about_new_version_title: '🔄 Automatic updates',
    about_new_version_text:  'Weeklyst regularly receives small improvements. When an update is available you will see a notification at the bottom of the app. Tap it to refresh — you do not need to remove and re-add the app to your home screen.',
    about_new_login_title:   '👨‍👩‍👧 Simplified joining',
    about_new_login_text:    'Family members no longer need their own email address to join. Joining now only requires a family code, a name and a password. Logging in works the same way afterwards. The family admin continues to log in with an email address and password. If a family member forgets their password, the system sends a reset link to the admin, who can forward it to the family member.',
    about_new_cards_title:   '🏪 Loyalty cards',
    about_new_cards_text:    'Store your bonus and loyalty cards in the app. Scan the barcode or QR code using your phone camera, or enter the number manually. Tap a card to display it full screen at the checkout. Supports barcodes (EAN-13, Code 128) and QR codes, such as those from AH, ANWB, Gamma, Karwei and Praxis. Cards are visible to the whole family.',
    about_new_security_title: '🔒 Extra form security',
    about_new_security_text:  'All forms in the app are protected with additional security layers that detect and block automated attacks. This works entirely in the background and is not noticeable to regular users.',
    about_new_push_title:     '🔔 Push notifications',
    about_new_push_text:      'Receive a notification on your phone when a family member has updated the list. The app waits 2 minutes after the last change before sending the notification — so you get one notification per editing session instead of one for every small change. A red badge also appears on the app icon. Notifications are opt-in: you can enable them in Settings.',
    about_new_invite_title:   '🔗 Invite via link',
    about_new_invite_text:    'Inviting family members is now even easier. Tap the "Invite" button in Settings and share the link via WhatsApp, iMessage or email. The recipient only needs to fill in a name and password — the family code is already included in the link.',
    about_new_owners_title:   '👑 Multiple admins',
    about_new_owners_text:    'You can make multiple family members admin, just like you can have multiple group owners in WhatsApp. Admins can add and remove members and assign or revoke the admin role. Regular members can leave the family via Settings.',
    about_new_days_title:     '📅 Fixed weekdays and start day setting',
    about_new_days_text:      'The days in the meal planner are now fixed names (Mo, Tu, We...) instead of a free text field. In Settings you can choose which day your week starts on — the other days are automatically filled in the correct order. Today is shown in bold so you can spot it instantly.',
    about_new_week_reset_title: '🛒 New week only clears groceries',
    about_new_week_reset_text:  'When you start a new week only the shopping list is cleared. The meal planner and ideas list are fully preserved — handy for looking back at what you ate the week before.',
    about_new_scroll_title:   '🔴 Tap version number to go to update',
    about_new_scroll_text:    'When an update is available a red dot appears next to the version number at the bottom of the app. Tap it and the settings open automatically with the update button in view — no need to scroll yourself.',

    // ── Installatie pagina ─────────────────────────────────
    install_title:     '📱 Install Weeklyst',
    install_sub:       'Add Weeklyst to your home screen for the best experience — works like a real app, without the App Store.',
    install_tab_ios:   '🍎 iPhone / iPad',
    install_tab_android: '🤖 Android',
    install_ios_1_title: 'Open Safari',
    install_ios_1_text:  'Go to <strong>weeklyst.nl</strong> in Safari on your iPhone or iPad.<br><em>Note: use Safari, not Chrome or another browser.</em>',
    install_ios_2_title: 'Tap the Share icon',
    install_ios_2_text:  'Tap the <span class="step-icon">&#11014;</span> icon at the bottom of your screen (square with arrow pointing up).',
    install_ios_3_title: 'Choose "Add to Home Screen"',
    install_ios_3_text:  'Scroll down in the menu and tap <strong>"Add to Home Screen"</strong> (with a &#10133; icon).',
    install_ios_4_title: 'Tap "Add"',
    install_ios_4_text:  'The name is already set to "Weeklyst". Tap <strong>"Add"</strong> in the top right.',
    install_ios_5_title: 'Done! 🎉',
    install_ios_5_text:  'Weeklyst is now on your home screen as a real app with the blue basket icon.',
    install_ios_tip:     '<strong>Tip:</strong> Always open the app via the home screen icon for the best experience.',
    install_and_1_title: 'Open Chrome',
    install_and_1_text:  'Go to <strong>weeklyst.nl</strong> in Google Chrome on your Android phone or tablet.',
    install_and_2_title: 'Tap the menu',
    install_and_2_text:  'Tap the three dots <span class="step-icon">&#8942;</span> in the top right of Chrome.',
    install_and_3_title: 'Choose "Add to home screen"',
    install_and_3_text:  'Tap <strong>"Add to home screen"</strong> or <strong>"Install app"</strong> in the menu.',
    install_and_4_title: 'Confirm',
    install_and_4_text:  'Tap <strong>"Add"</strong> in the popup window.',
    install_and_5_title: 'Done! 🎉',
    install_and_5_text:  'Weeklyst is now on your home screen. You will find the icon among your other apps.',
    install_and_tip:     '<strong>Samsung browser?</strong> Tap the three lines at the bottom → "Add page to" → "Home screen".',
    install_benefits_title: 'Why add to your home screen?',
    install_b1:          'Faster startup — direct to the app',
    install_b2:          'Feels like a real app — no address bar',
    install_b3:          'Always at hand for your family',
    install_b4:          'No App Store needed — free and always up-to-date',

    // ── Privacy pagina ─────────────────────────────────────
    privacy_title:      'Privacy Policy',
    privacy_date:       'Version 1.0 — June 2025',
    privacy_summary_label: 'In short:',
    privacy_summary_text: 'Weeklyst only stores what is needed to make the app work. No ads, no tracking, no selling of your data. Your data stays in the Netherlands.',
    privacy_summary:    'In short: Weeklyst only stores what is needed to make the app work. No ads, no tracking, no selling of your data. Your data stays in the Netherlands.',
    privacy_s1_title:   '1. Who are we?',
    privacy_s1_text:    'Weeklyst is a personal project — a simple family planner for meals and groceries, hosted on Dutch servers.',
    privacy_s1_text:    'Weeklyst is a personal project — a simple family planner for meals and groceries, hosted on Dutch servers.',
    privacy_contact:    'Contact:',
    privacy_s2_title:   '2. What data do we store?',
    privacy_s2_intro:   'We only store the data needed to make the app work:',
    privacy_s2_1:       'Your email address (for login and verification)',
    privacy_s2_2:       'Your name (shown in the app when changes are made)',
    privacy_s2_3:       'The name of your family',
    privacy_s2_4:       'The content of your weekly planner (meals, groceries, ideas)',
    privacy_s2_5:       'An encrypted password (only for password login)',
    privacy_s3_title:   '3. What we do NOT do',
    privacy_s3_1:       'We do not sell your data to third parties',
    privacy_s3_2:       'We do not use advertising networks',
    privacy_s3_3:       'We do not track your behavior (no Google Analytics, no pixels)',
    privacy_s3_4:       'We do not share your data with other companies',
    privacy_s3_5:       'We do not send marketing emails',
    privacy_s4_title:   '4. Where is your data stored?',
    privacy_s4_text:    'All data is stored on a server in the Netherlands at Antagonist, a Dutch hosting provider. The data does not leave the Netherlands.',
    privacy_s4_text:    'All data is stored on a server in the Netherlands at Antagonist, a Dutch hosting provider. The data does not leave the Netherlands.',
    privacy_s5_title:   '5. How long do we keep your data?',
    privacy_s5_text:    'Your data is kept as long as your account is active. When you delete your account, all associated data will be permanently deleted within 30 days.',
    privacy_s5_text:    'Your data is kept as long as your account is active. When you delete your account, all associated data will be permanently deleted within 30 days.',
    privacy_s6_title:   '6. Cookies',
    privacy_s6_text:    'Weeklyst uses one functional cookie to keep you logged in. This cookie contains no personal information and is not used for tracking or advertising. The cookie automatically expires after 30 days or when you log out.',
    privacy_s6_text:    'Weeklyst gebruikt één functioneel cookie om je ingelogd te houden. Dit cookie bevat geen persoonlijke informatie en wordt niet gebruikt voor tracking of advertenties. Het cookie verdwijnt automatisch na 30 dagen of wanneer je uitlogt.',
    privacy_s6_text:    'Weeklyst uses one functional cookie to keep you logged in. This cookie contains no personal information and is not used for tracking or advertising. The cookie automatically expires after 30 days or when you log out.',
    privacy_s7_title:   '7. Security',
    privacy_s7_text:    'All connections to Weeklyst use HTTPS. Passwords are stored encrypted using a strong algorithm (bcrypt). Sessions are secured with a signed cookie.',
    privacy_s7_text:    'All connections to Weeklyst use HTTPS. Passwords are stored encrypted using a strong algorithm (bcrypt). Sessions are secured with a signed cookie.',
    privacy_s8_title:   '8. Your rights (GDPR)',
    privacy_s8_intro:   'Under the GDPR you have the following rights:',
    privacy_s8_1:       'Right to access your data',
    privacy_s8_2:       'Right to correct inaccurate data',
    privacy_s8_3:       'Right to delete your data',
    privacy_s8_4:       'Right to data portability',
    privacy_s8_5:       'Right to object',
    privacy_s8_outro:   'Contact us at info@weeklyst.nl to submit a request. We will respond within 30 days.',
    privacy_s9_title:   '9. Changes',
    privacy_s9_text:    'We may update this privacy policy. You will be notified by email of any significant changes.',
    privacy_s9_text:    'We may update this privacy policy. You will be notified by email of any significant changes.',
    privacy_s10_title:  '10. Contact',
    privacy_s10_text:   'Do you have questions about your privacy or want to submit a request?',
    privacy_s10_text:   'Heb je vragen over jouw privacy of wil je een verzoek indienen?',
    privacy_s10_text:   'Do you have questions about your privacy or want to submit a request?',
    privacy_s10_email:  'Email:',
  }

};

// ── Taalmotor ──────────────────────────────────────────────────────────────

let currentLang = 'nl';

function getLang() {
  const m = document.cookie.match(/(?:^|;\s*)wl_lang=([^;]*)/);
  if (m) return decodeURIComponent(m[1]);
  try { return localStorage.getItem('wl_lang') || null; } catch(e) {}
  return null;
}

function setLang(lang) {
  const exp = new Date(Date.now() + 365 * 864e5).toUTCString();
  document.cookie = 'wl_lang=' + lang + '; expires=' + exp + '; path=/; SameSite=Lax';
  try { localStorage.setItem('wl_lang', lang); } catch(e) {}
}

/** Geeft de vertaling voor een sleutel terug */
function t(key) {
  return LANG[currentLang]?.[key] ?? LANG['nl']?.[key] ?? key;
}

/** Past alle data-i18n elementen aan */
function applyTranslations() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    const val = t(key);
    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
      el.placeholder = val;
    } else {
      el.textContent = val;
    }
  });
  // HTML vertalingen (voor tekst met opmaak zoals <strong>, <em>)
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    el.innerHTML = t(el.dataset.i18nHtml);
  });
  // Taalknop bijwerken
  document.querySelectorAll('.lang-toggle').forEach(btn => {
    btn.textContent = currentLang === 'nl' ? 'EN' : 'NL';
  });
}

/** Initialiseer taal bij laden van de pagina */
function initLang() {
  const saved = getLang();
  if (saved && LANG[saved]) {
    currentLang = saved;
  } else {
    // Auto-detectie op basis van browsertaal
    currentLang = navigator.language?.toLowerCase().startsWith('nl') ? 'nl' : 'en';
  }
  applyTranslations();
}

/** Wissel taal en pas direct toe */
function toggleLang() {
  currentLang = currentLang === 'nl' ? 'en' : 'nl';
  setLang(currentLang);
  applyTranslations();
  // Geef renderAll door als het bestaat (voor app.html)
  if (typeof renderAll === 'function') renderAll();
}
